# Generated by Django 2.1 on 2018-08-22 14:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import issuances.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('shorthand', models.SlugField(max_length=3, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('num', models.IntegerField(default=issuances.models.ChapterSection.number, unique=True, verbose_name='Section Number')),
                ('content', ckeditor.fields.RichTextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuances.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('banner_image', models.ImageField(blank=True, default='media/images/placeholder_banner.jpg', null=True, upload_to='media/issuance_banners/', verbose_name='Banner Image')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('publish', models.DateTimeField(blank=True, default=None, null=True, verbose_name='published')),
                ('legacy_id', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Legacy ID (Leave blank if not legacy)')),
                ('lastmodified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('issuance_number', models.IntegerField(blank=True, default=issuances.models.Issuance.i_number, null=True, verbose_name='Issuance Number')),
                ('chapter', models.ManyToManyField(to='issuances.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='IssuanceContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
                ('issuance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuances.Issuance')),
            ],
        ),
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='attachment',
            name='issuance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuances.Issuance'),
        ),
    ]
