# Generated by Django 2.1.3 on 2018-11-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersection',
            name='num',
            field=models.CharField(max_length=10, unique=True, verbose_name='Section Number'),
        ),
    ]
