# Generated by Django 2.1 on 2018-09-24 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchModel',
        ),
    ]
