# Generated by Django 2.1.3 on 2018-11-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0002_delete_searchmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachCategory',
            field=models.CharField(blank=True, choices=[('Paid Family Leave Program', 'Paid Family Leave Program'), ('Compensation', 'Compensation'), ('Employment', 'Employment'), ('HR Advisor Tools', 'HR Advisor Tools'), ('Employee Relations', 'Employee Relations'), ('Leave', 'Leave')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachType',
            field=models.CharField(blank=True, choices=[('Form', 'Form'), ('Template', 'Template'), ('Misc', 'Misc')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issuancecontent',
            name='issuance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuance_content', to='issuances.Issuance'),
        ),
    ]
