# Generated by Django 2.1.3 on 2018-11-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0003_auto_20181129_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptersection',
            options={},
        ),
        migrations.RemoveField(
            model_name='chaptersection',
            name='position',
        ),
    ]
