# Generated by Django 2.1.3 on 2018-11-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0005_auto_20181129_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersection',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='position'),
        ),
    ]
